amazonProperties:
  endpointUrl: https://employee-portal-file.s3.ap-south-1.amazonaws.com
  accessKey: AKIAU6GDXF3NGP562HFQ
  secretKey: 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
  bucketName: employee-portal-file